server: 
  port: 4399
soul:
  http:
    zookeeperUrl: 39.107.109.17:2181
    adminUrl: http://v9spvbniswv.vshidai.top
    contextPath: /open
    appName: watermark
    
spring:
  redis:
    host: 123.57.141.60
    port: 7379
    password: yanhuakang7379
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 10000
    database: 0